// Command pricing-simulate is a standalone report generator for the
// Pricing Simulation Engine (backend/services/pricing/simulation). It is
// NOT part of the production Pricing Service — nothing in cmd/server
// imports this package, and this package imports nothing from cmd/server,
// grpc, or app. Running it can never affect a running Pricing Service
// instance; it only reads the simulation package's pure functions and
// writes a markdown report to disk.
//
// Usage (from backend/services/pricing):
//
//	go run ./cmd/pricing-simulate > ../../../docs/business/PRICING_SIMULATION_REPORT.md
//
// or, to write the file directly:
//
//	go run ./cmd/pricing-simulate -out ../../../docs/business/PRICING_SIMULATION_REPORT.md
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/fairride/pricing/simulation"
)

func main() {
	outPath := flag.String("out", "", "file path to write the report to; empty = stdout")
	flag.Parse()

	var b strings.Builder
	writeReport(&b)

	if *outPath == "" {
		fmt.Print(b.String())
		return
	}
	if err := os.WriteFile(*outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "pricing-simulate: failed to write report:", err)
		os.Exit(1)
	}
	fmt.Println("pricing-simulate: wrote report to", *outPath)
}

func writeReport(b *strings.Builder) {
	scenarios := simulation.AllScenarios()
	sim := simulation.NewDefaultSimulator()

	fmt.Fprintf(b, "# Panda Pricing Simulation — Raw Engine Output\n\n")
	fmt.Fprintf(b, "Generated by `cmd/pricing-simulate`. %d scenarios.\n\n", len(scenarios))

	fmt.Fprintf(b, "## Scenarios\n\n")
	fmt.Fprintf(b, "| # | Scenario | Vehicle | Customer Total | Net Driver | Platform Profit | Margin | Warnings |\n")
	fmt.Fprintf(b, "|---|---|---|---|---|---|---|---|\n")
	for i, sc := range scenarios {
		fb, err := sim.Simulate(sc.Input)
		if err != nil {
			fmt.Fprintf(b, "| %d | %s | ERROR | %v |  |  |  |  |\n", i+1, sc.Name, err)
			continue
		}
		fmt.Fprintf(b, "| %d | %s | %s | %d | %d | %d | %.1f%% | %s |\n",
			i+1, sc.Name, fb.VehicleType, fb.CustomerTotal, fb.NetDriver, fb.Profit, fb.MarginPct*100,
			strings.Join(fb.Warnings, "; "))
	}

	fmt.Fprintf(b, "\n## Optimizer (BƯỚC 5)\n\n")
	scores := simulation.Optimize(scenarios, simulation.DefaultCandidateGrid())
	fmt.Fprintf(b, "| Rank | Candidate | Driver-beats-market | Cheaper-than-market | Agg margin |\n")
	fmt.Fprintf(b, "|---|---|---|---|---|\n")
	for i, s := range scores {
		fmt.Fprintf(b, "| %d | %s | %d/%d | %d/%d | %.2f%% |\n",
			i+1, s.Candidate.Label, s.DriverEarnsMoreCount, s.TotalComparisons,
			s.CheaperThanMarketCount, s.TotalComparisons, s.AggMarginPct*100)
	}

	fmt.Fprintf(b, "\n## Sensitivity (BƯỚC 6)\n\n")
	fuel := simulation.RunFuelShock(scenarios, 0.20)
	fmt.Fprintf(b, "- Fuel +20%%: effective driver take eroded %.1f%%, still positive for all trips: %v\n",
		fuel.EffectiveTakeErodedPct*100, fuel.StillPositiveForAllTrips)
	promo := simulation.RunPromotionShock(scenarios, 1.5)
	fmt.Fprintf(b, "- Voucher spend +50%%: aggregate profit %d → %d, still breakeven: %v\n",
		promo.AggProfitBefore, promo.AggProfitAfter, promo.StillBreakeven)
	comm := simulation.RunCommissionShock(scenarios, 0.16)
	fmt.Fprintf(b, "- Bronze commission 20%%→16%%: aggregate profit %d → %d, driver income %d → %d\n",
		comm.AggProfitBefore, comm.AggProfitAfter, comm.AggDriverIncomeBefore, comm.AggDriverIncomeAfter)
	supply := simulation.RunDriverSupplyDoubled(scenarios)
	fmt.Fprintf(b, "- Driver supply ×2 (DSR halved): avg surge %.2f → %.2f, avg driver income %.0f → %.0f (%.1f%%)\n",
		supply.AvgSurgeMultiplierBefore, supply.AvgSurgeMultiplierAfter,
		supply.AvgDriverIncomeBefore, supply.AvgDriverIncomeAfter, supply.DriverIncomeChangePct*100)
	demand := simulation.RunRiderDemand5x(scenarios)
	fmt.Fprintf(b, "- Rider demand ×5 (DSR ×5): avg surge %.2f → %.2f, price-cap hits %d → %d, max-surge hits %d\n",
		demand.AvgSurgeMultiplierBefore, demand.AvgSurgeMultiplierAfter,
		demand.PriceCapHitCountBefore, demand.PriceCapHitCountAfter, demand.MaxSurgeHitCountAfter)
}
