// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: dispatch.proto

package dispatchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DispatchService_RequestDispatch_FullMethodName      = "/dispatch.v1.DispatchService/RequestDispatch"
	DispatchService_AcceptTrip_FullMethodName           = "/dispatch.v1.DispatchService/AcceptTrip"
	DispatchService_RejectTrip_FullMethodName           = "/dispatch.v1.DispatchService/RejectTrip"
	DispatchService_UpdateDriverLocation_FullMethodName = "/dispatch.v1.DispatchService/UpdateDriverLocation"
	DispatchService_GetDispatchStatus_FullMethodName    = "/dispatch.v1.DispatchService/GetDispatchStatus"
)

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatchServiceClient interface {
	// RequestDispatch initiates a dispatch job for a trip.
	// Called by the trip service when a trip reaches Searching status.
	RequestDispatch(ctx context.Context, in *RequestDispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// AcceptTrip lets a driver accept the current offer.
	AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// RejectTrip lets a driver decline the current offer.
	// Dispatch immediately retries with the next nearest driver.
	RejectTrip(ctx context.Context, in *RejectTripRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// UpdateDriverLocation updates a driver's GPS coordinates for dispatch matching.
	// Drivers should call this periodically while online.
	UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationRequest, opts ...grpc.CallOption) (*UpdateDriverLocationResponse, error)
	// GetDispatchStatus returns the current dispatch job for a trip.
	GetDispatchStatus(ctx context.Context, in *GetDispatchStatusRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) RequestDispatch(ctx context.Context, in *RequestDispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, DispatchService_RequestDispatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, DispatchService_AcceptTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) RejectTrip(ctx context.Context, in *RejectTripRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, DispatchService_RejectTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) UpdateDriverLocation(ctx context.Context, in *UpdateDriverLocationRequest, opts ...grpc.CallOption) (*UpdateDriverLocationResponse, error) {
	out := new(UpdateDriverLocationResponse)
	err := c.cc.Invoke(ctx, DispatchService_UpdateDriverLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) GetDispatchStatus(ctx context.Context, in *GetDispatchStatusRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, DispatchService_GetDispatchStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility
type DispatchServiceServer interface {
	// RequestDispatch initiates a dispatch job for a trip.
	// Called by the trip service when a trip reaches Searching status.
	RequestDispatch(context.Context, *RequestDispatchRequest) (*DispatchResponse, error)
	// AcceptTrip lets a driver accept the current offer.
	AcceptTrip(context.Context, *AcceptTripRequest) (*DispatchResponse, error)
	// RejectTrip lets a driver decline the current offer.
	// Dispatch immediately retries with the next nearest driver.
	RejectTrip(context.Context, *RejectTripRequest) (*DispatchResponse, error)
	// UpdateDriverLocation updates a driver's GPS coordinates for dispatch matching.
	// Drivers should call this periodically while online.
	UpdateDriverLocation(context.Context, *UpdateDriverLocationRequest) (*UpdateDriverLocationResponse, error)
	// GetDispatchStatus returns the current dispatch job for a trip.
	GetDispatchStatus(context.Context, *GetDispatchStatusRequest) (*DispatchResponse, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatchServiceServer struct {
}

func (UnimplementedDispatchServiceServer) RequestDispatch(context.Context, *RequestDispatchRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDispatch not implemented")
}
func (UnimplementedDispatchServiceServer) AcceptTrip(context.Context, *AcceptTripRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptTrip not implemented")
}
func (UnimplementedDispatchServiceServer) RejectTrip(context.Context, *RejectTripRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectTrip not implemented")
}
func (UnimplementedDispatchServiceServer) UpdateDriverLocation(context.Context, *UpdateDriverLocationRequest) (*UpdateDriverLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDriverLocation not implemented")
}
func (UnimplementedDispatchServiceServer) GetDispatchStatus(context.Context, *GetDispatchStatusRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispatchStatus not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_RequestDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).RequestDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_RequestDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).RequestDispatch(ctx, req.(*RequestDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_AcceptTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).AcceptTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_AcceptTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).AcceptTrip(ctx, req.(*AcceptTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_RejectTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).RejectTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_RejectTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).RejectTrip(ctx, req.(*RejectTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_UpdateDriverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).UpdateDriverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_UpdateDriverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).UpdateDriverLocation(ctx, req.(*UpdateDriverLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_GetDispatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDispatchStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).GetDispatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_GetDispatchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).GetDispatchStatus(ctx, req.(*GetDispatchStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatch.v1.DispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDispatch",
			Handler:    _DispatchService_RequestDispatch_Handler,
		},
		{
			MethodName: "AcceptTrip",
			Handler:    _DispatchService_AcceptTrip_Handler,
		},
		{
			MethodName: "RejectTrip",
			Handler:    _DispatchService_RejectTrip_Handler,
		},
		{
			MethodName: "UpdateDriverLocation",
			Handler:    _DispatchService_UpdateDriverLocation_Handler,
		},
		{
			MethodName: "GetDispatchStatus",
			Handler:    _DispatchService_GetDispatchStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatch.proto",
}
