// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: trip.proto

package trippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TripService_CreateTrip_FullMethodName        = "/trip.v1.TripService/CreateTrip"
	TripService_CancelTrip_FullMethodName        = "/trip.v1.TripService/CancelTrip"
	TripService_GetTrip_FullMethodName           = "/trip.v1.TripService/GetTrip"
	TripService_MarkDriverArrived_FullMethodName = "/trip.v1.TripService/MarkDriverArrived"
	TripService_StartTrip_FullMethodName         = "/trip.v1.TripService/StartTrip"
	TripService_CompleteTrip_FullMethodName      = "/trip.v1.TripService/CompleteTrip"
	TripService_InitiatePayment_FullMethodName   = "/trip.v1.TripService/InitiatePayment"
	TripService_PayTrip_FullMethodName           = "/trip.v1.TripService/PayTrip"
	TripService_ListTripsByRider_FullMethodName  = "/trip.v1.TripService/ListTripsByRider"
	TripService_ListTripsByDriver_FullMethodName = "/trip.v1.TripService/ListTripsByDriver"
	// Delivery V1 Phase 4 (docs/business/DELIVERY_V1_DESIGN.md) — additive.
	TripService_PickupParcel_FullMethodName     = "/trip.v1.TripService/PickupParcel"
	TripService_StartDelivery_FullMethodName    = "/trip.v1.TripService/StartDelivery"
	TripService_CompleteDelivery_FullMethodName = "/trip.v1.TripService/CompleteDelivery"
	// Production hardening (P0-1): AcceptDelivery closes the CREATED→ACCEPTED
	// gap — AcceptDispatchOfferUseCase (Booking) only updates Dispatch/Trip,
	// never the in-memory Delivery aggregate that only the Trip service
	// process holds, so it must call this RPC explicitly after accept.
	TripService_AcceptDelivery_FullMethodName = "/trip.v1.TripService/AcceptDelivery"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	// CreateTrip creates a new trip in Pending status.
	CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// CancelTrip cancels a trip that has not yet started or completed.
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// GetTrip returns a trip by its ID.
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// MarkDriverArrived transitions a trip from DriverAssigned to DriverArrived.
	MarkDriverArrived(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// StartTrip transitions a trip from DriverAssigned/DriverArrived to InProgress.
	StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// CompleteTrip transitions a trip from InProgress to Completed and records the fare.
	// The caller is responsible for computing the fare before calling this RPC.
	CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// InitiatePayment transitions a completed trip to PaymentPending.
	InitiatePayment(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// PayTrip processes payment and transitions PaymentPending → Settled.
	// req.reason carries the payment method ("cash" | "wallet").
	PayTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// ListTripsByRider returns all trips for a rider, newest first.
	ListTripsByRider(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*TripsResponse, error)
	// ListTripsByDriver returns all trips for a driver, newest first.
	ListTripsByDriver(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*TripsResponse, error)
	// PickupParcel transitions a Delivery from Accepted to ParcelPickedUp,
	// and the linked Trip to InProgress. Delivery V1 Phase 4.
	PickupParcel(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// StartDelivery transitions a Delivery from ParcelPickedUp to InDelivery.
	StartDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// CompleteDelivery marks a Delivery Delivered then Completed.
	CompleteDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// AcceptDelivery transitions a Delivery from Created to Accepted.
	// No-op (not an error) if the trip isn't a delivery, or if the
	// delivery is already past Created — idempotent, safe to call more
	// than once for the same trip.
	AcceptDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CreateTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CancelTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_GetTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) MarkDriverArrived(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_MarkDriverArrived_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_StartTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CompleteTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) InitiatePayment(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_InitiatePayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PayTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_PayTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListTripsByRider(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*TripsResponse, error) {
	out := new(TripsResponse)
	err := c.cc.Invoke(ctx, TripService_ListTripsByRider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListTripsByDriver(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*TripsResponse, error) {
	out := new(TripsResponse)
	err := c.cc.Invoke(ctx, TripService_ListTripsByDriver_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PickupParcel(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_PickupParcel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) StartDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_StartDelivery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CompleteDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CompleteDelivery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptDelivery(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptDelivery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility
type TripServiceServer interface {
	// CreateTrip creates a new trip in Pending status.
	CreateTrip(context.Context, *CreateTripRequest) (*TripResponse, error)
	// CancelTrip cancels a trip that has not yet started or completed.
	CancelTrip(context.Context, *CancelTripRequest) (*TripResponse, error)
	// GetTrip returns a trip by its ID.
	GetTrip(context.Context, *GetTripRequest) (*TripResponse, error)
	// MarkDriverArrived transitions a trip from DriverAssigned to DriverArrived.
	MarkDriverArrived(context.Context, *GetTripRequest) (*TripResponse, error)
	// StartTrip transitions a trip from DriverAssigned/DriverArrived to InProgress.
	StartTrip(context.Context, *StartTripRequest) (*TripResponse, error)
	// CompleteTrip transitions a trip from InProgress to Completed and records the fare.
	// The caller is responsible for computing the fare before calling this RPC.
	CompleteTrip(context.Context, *CompleteTripRequest) (*TripResponse, error)
	// InitiatePayment transitions a completed trip to PaymentPending.
	InitiatePayment(context.Context, *GetTripRequest) (*TripResponse, error)
	// PayTrip processes payment and transitions PaymentPending → Settled.
	// req.reason carries the payment method ("cash" | "wallet").
	PayTrip(context.Context, *CancelTripRequest) (*TripResponse, error)
	// ListTripsByRider returns all trips for a rider, newest first.
	ListTripsByRider(context.Context, *ListTripsRequest) (*TripsResponse, error)
	// ListTripsByDriver returns all trips for a driver, newest first.
	ListTripsByDriver(context.Context, *ListTripsRequest) (*TripsResponse, error)
	// PickupParcel transitions a Delivery from Accepted to ParcelPickedUp,
	// and the linked Trip to InProgress. Delivery V1 Phase 4.
	PickupParcel(context.Context, *GetTripRequest) (*TripResponse, error)
	// StartDelivery transitions a Delivery from ParcelPickedUp to InDelivery.
	StartDelivery(context.Context, *GetTripRequest) (*TripResponse, error)
	// CompleteDelivery marks a Delivery Delivered then Completed.
	CompleteDelivery(context.Context, *GetTripRequest) (*TripResponse, error)
	// AcceptDelivery transitions a Delivery from Created to Accepted.
	// No-op (not an error) if the trip isn't a delivery, or if the
	// delivery is already past Created — idempotent, safe to call more
	// than once for the same trip.
	AcceptDelivery(context.Context, *GetTripRequest) (*TripResponse, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTripServiceServer struct {
}

func (UnimplementedTripServiceServer) CreateTrip(context.Context, *CreateTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *CancelTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) GetTrip(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServiceServer) MarkDriverArrived(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkDriverArrived not implemented")
}
func (UnimplementedTripServiceServer) StartTrip(context.Context, *StartTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTrip not implemented")
}
func (UnimplementedTripServiceServer) CompleteTrip(context.Context, *CompleteTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTrip not implemented")
}
func (UnimplementedTripServiceServer) InitiatePayment(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (UnimplementedTripServiceServer) PayTrip(context.Context, *CancelTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayTrip not implemented")
}
func (UnimplementedTripServiceServer) ListTripsByRider(context.Context, *ListTripsRequest) (*TripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTripsByRider not implemented")
}
func (UnimplementedTripServiceServer) ListTripsByDriver(context.Context, *ListTripsRequest) (*TripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTripsByDriver not implemented")
}
func (UnimplementedTripServiceServer) PickupParcel(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PickupParcel not implemented")
}
func (UnimplementedTripServiceServer) StartDelivery(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDelivery not implemented")
}
func (UnimplementedTripServiceServer) CompleteDelivery(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteDelivery not implemented")
}
func (UnimplementedTripServiceServer) AcceptDelivery(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptDelivery not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateTrip(ctx, req.(*CreateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_MarkDriverArrived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).MarkDriverArrived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_MarkDriverArrived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).MarkDriverArrived(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_StartTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).StartTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_StartTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).StartTrip(ctx, req.(*StartTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CompleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CompleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CompleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CompleteTrip(ctx, req.(*CompleteTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_InitiatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).InitiatePayment(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PayTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PayTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PayTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PayTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListTripsByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListTripsByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListTripsByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListTripsByRider(ctx, req.(*ListTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListTripsByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListTripsByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListTripsByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListTripsByDriver(ctx, req.(*ListTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PickupParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PickupParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PickupParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PickupParcel(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_StartDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).StartDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_StartDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).StartDelivery(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CompleteDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CompleteDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CompleteDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CompleteDelivery(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptDelivery(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.v1.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TripService_CreateTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _TripService_GetTrip_Handler,
		},
		{
			MethodName: "MarkDriverArrived",
			Handler:    _TripService_MarkDriverArrived_Handler,
		},
		{
			MethodName: "StartTrip",
			Handler:    _TripService_StartTrip_Handler,
		},
		{
			MethodName: "CompleteTrip",
			Handler:    _TripService_CompleteTrip_Handler,
		},
		{
			MethodName: "InitiatePayment",
			Handler:    _TripService_InitiatePayment_Handler,
		},
		{
			MethodName: "PayTrip",
			Handler:    _TripService_PayTrip_Handler,
		},
		{
			MethodName: "ListTripsByRider",
			Handler:    _TripService_ListTripsByRider_Handler,
		},
		{
			MethodName: "ListTripsByDriver",
			Handler:    _TripService_ListTripsByDriver_Handler,
		},
		{
			MethodName: "PickupParcel",
			Handler:    _TripService_PickupParcel_Handler,
		},
		{
			MethodName: "StartDelivery",
			Handler:    _TripService_StartDelivery_Handler,
		},
		{
			MethodName: "CompleteDelivery",
			Handler:    _TripService_CompleteDelivery_Handler,
		},
		{
			MethodName: "AcceptDelivery",
			Handler:    _TripService_AcceptDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip.proto",
}
