// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: pricing.proto

package pricingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PricingService_EstimateFare_FullMethodName       = "/pricing.v1.PricingService/EstimateFare"
	PricingService_CalculateFinalFare_FullMethodName = "/pricing.v1.PricingService/CalculateFinalFare"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PricingServiceClient interface {
	// EstimateFare calculates an upfront fare estimate before the trip starts.
	EstimateFare(ctx context.Context, in *EstimateFareRequest, opts ...grpc.CallOption) (*FareResponse, error)
	// CalculateFinalFare calculates the fare after trip completion using actual values.
	// Uses the same formula as EstimateFare — no deviation penalty in MVP.
	CalculateFinalFare(ctx context.Context, in *CalculateFinalFareRequest, opts ...grpc.CallOption) (*FareResponse, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) EstimateFare(ctx context.Context, in *EstimateFareRequest, opts ...grpc.CallOption) (*FareResponse, error) {
	out := new(FareResponse)
	err := c.cc.Invoke(ctx, PricingService_EstimateFare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) CalculateFinalFare(ctx context.Context, in *CalculateFinalFareRequest, opts ...grpc.CallOption) (*FareResponse, error) {
	out := new(FareResponse)
	err := c.cc.Invoke(ctx, PricingService_CalculateFinalFare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility
type PricingServiceServer interface {
	// EstimateFare calculates an upfront fare estimate before the trip starts.
	EstimateFare(context.Context, *EstimateFareRequest) (*FareResponse, error)
	// CalculateFinalFare calculates the fare after trip completion using actual values.
	// Uses the same formula as EstimateFare — no deviation penalty in MVP.
	CalculateFinalFare(context.Context, *CalculateFinalFareRequest) (*FareResponse, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (UnimplementedPricingServiceServer) EstimateFare(context.Context, *EstimateFareRequest) (*FareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateFare not implemented")
}
func (UnimplementedPricingServiceServer) CalculateFinalFare(context.Context, *CalculateFinalFareRequest) (*FareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFinalFare not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_EstimateFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).EstimateFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_EstimateFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).EstimateFare(ctx, req.(*EstimateFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_CalculateFinalFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFinalFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CalculateFinalFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_CalculateFinalFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CalculateFinalFare(ctx, req.(*CalculateFinalFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricing.v1.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimateFare",
			Handler:    _PricingService_EstimateFare_Handler,
		},
		{
			MethodName: "CalculateFinalFare",
			Handler:    _PricingService_CalculateFinalFare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing.proto",
}
