// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: booking.proto

package bookingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BookingService_BookRide_FullMethodName            = "/booking.v1.BookingService/BookRide"
	BookingService_AcceptDispatchOffer_FullMethodName = "/booking.v1.BookingService/AcceptDispatchOffer"
	BookingService_RejectDispatchOffer_FullMethodName = "/booking.v1.BookingService/RejectDispatchOffer"
	BookingService_StartTrip_FullMethodName           = "/booking.v1.BookingService/StartTrip"
	BookingService_FinishTrip_FullMethodName          = "/booking.v1.BookingService/FinishTrip"
	BookingService_GetBookingDetails_FullMethodName   = "/booking.v1.BookingService/GetBookingDetails"
)

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingServiceClient interface {
	// BookRide creates a trip and immediately requests dispatch.
	// Returns as soon as the dispatch search has been triggered (status: searching).
	BookRide(ctx context.Context, in *BookRideRequest, opts ...grpc.CallOption) (*BookRideResponse, error)
	// AcceptDispatchOffer is called by the driver to accept the pending trip offer.
	// Delegates to the Dispatch service; trip transitions to driver_assigned.
	AcceptDispatchOffer(ctx context.Context, in *AcceptDispatchOfferRequest, opts ...grpc.CallOption) (*BookingActionResponse, error)
	// RejectDispatchOffer is called by the driver to reject the pending offer.
	// Dispatch retries with the next nearest driver.
	RejectDispatchOffer(ctx context.Context, in *RejectDispatchOfferRequest, opts ...grpc.CallOption) (*BookingActionResponse, error)
	// StartTrip is called by the driver when they begin the ride.
	// Trip transitions from driver_assigned/driver_arrived to in_progress.
	StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*BookingActionResponse, error)
	// FinishTrip is called by the driver when the ride ends.
	// Computes the final fare via Pricing, then marks the trip completed.
	FinishTrip(ctx context.Context, in *FinishTripRequest, opts ...grpc.CallOption) (*FinishedTripResponse, error)
	// GetBookingDetails returns the current state of a booking (trip + dispatch).
	GetBookingDetails(ctx context.Context, in *GetBookingDetailsRequest, opts ...grpc.CallOption) (*BookingDetailsResponse, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) BookRide(ctx context.Context, in *BookRideRequest, opts ...grpc.CallOption) (*BookRideResponse, error) {
	out := new(BookRideResponse)
	err := c.cc.Invoke(ctx, BookingService_BookRide_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) AcceptDispatchOffer(ctx context.Context, in *AcceptDispatchOfferRequest, opts ...grpc.CallOption) (*BookingActionResponse, error) {
	out := new(BookingActionResponse)
	err := c.cc.Invoke(ctx, BookingService_AcceptDispatchOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) RejectDispatchOffer(ctx context.Context, in *RejectDispatchOfferRequest, opts ...grpc.CallOption) (*BookingActionResponse, error) {
	out := new(BookingActionResponse)
	err := c.cc.Invoke(ctx, BookingService_RejectDispatchOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*BookingActionResponse, error) {
	out := new(BookingActionResponse)
	err := c.cc.Invoke(ctx, BookingService_StartTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) FinishTrip(ctx context.Context, in *FinishTripRequest, opts ...grpc.CallOption) (*FinishedTripResponse, error) {
	out := new(FinishedTripResponse)
	err := c.cc.Invoke(ctx, BookingService_FinishTrip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetBookingDetails(ctx context.Context, in *GetBookingDetailsRequest, opts ...grpc.CallOption) (*BookingDetailsResponse, error) {
	out := new(BookingDetailsResponse)
	err := c.cc.Invoke(ctx, BookingService_GetBookingDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
// All implementations must embed UnimplementedBookingServiceServer
// for forward compatibility
type BookingServiceServer interface {
	// BookRide creates a trip and immediately requests dispatch.
	// Returns as soon as the dispatch search has been triggered (status: searching).
	BookRide(context.Context, *BookRideRequest) (*BookRideResponse, error)
	// AcceptDispatchOffer is called by the driver to accept the pending trip offer.
	// Delegates to the Dispatch service; trip transitions to driver_assigned.
	AcceptDispatchOffer(context.Context, *AcceptDispatchOfferRequest) (*BookingActionResponse, error)
	// RejectDispatchOffer is called by the driver to reject the pending offer.
	// Dispatch retries with the next nearest driver.
	RejectDispatchOffer(context.Context, *RejectDispatchOfferRequest) (*BookingActionResponse, error)
	// StartTrip is called by the driver when they begin the ride.
	// Trip transitions from driver_assigned/driver_arrived to in_progress.
	StartTrip(context.Context, *StartTripRequest) (*BookingActionResponse, error)
	// FinishTrip is called by the driver when the ride ends.
	// Computes the final fare via Pricing, then marks the trip completed.
	FinishTrip(context.Context, *FinishTripRequest) (*FinishedTripResponse, error)
	// GetBookingDetails returns the current state of a booking (trip + dispatch).
	GetBookingDetails(context.Context, *GetBookingDetailsRequest) (*BookingDetailsResponse, error)
	mustEmbedUnimplementedBookingServiceServer()
}

// UnimplementedBookingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (UnimplementedBookingServiceServer) BookRide(context.Context, *BookRideRequest) (*BookRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookRide not implemented")
}
func (UnimplementedBookingServiceServer) AcceptDispatchOffer(context.Context, *AcceptDispatchOfferRequest) (*BookingActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptDispatchOffer not implemented")
}
func (UnimplementedBookingServiceServer) RejectDispatchOffer(context.Context, *RejectDispatchOfferRequest) (*BookingActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectDispatchOffer not implemented")
}
func (UnimplementedBookingServiceServer) StartTrip(context.Context, *StartTripRequest) (*BookingActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTrip not implemented")
}
func (UnimplementedBookingServiceServer) FinishTrip(context.Context, *FinishTripRequest) (*FinishedTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishTrip not implemented")
}
func (UnimplementedBookingServiceServer) GetBookingDetails(context.Context, *GetBookingDetailsRequest) (*BookingDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookingDetails not implemented")
}
func (UnimplementedBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {}

// UnsafeBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServiceServer will
// result in compilation errors.
type UnsafeBookingServiceServer interface {
	mustEmbedUnimplementedBookingServiceServer()
}

func RegisterBookingServiceServer(s grpc.ServiceRegistrar, srv BookingServiceServer) {
	s.RegisterService(&BookingService_ServiceDesc, srv)
}

func _BookingService_BookRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).BookRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_BookRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).BookRide(ctx, req.(*BookRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_AcceptDispatchOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptDispatchOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).AcceptDispatchOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_AcceptDispatchOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).AcceptDispatchOffer(ctx, req.(*AcceptDispatchOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_RejectDispatchOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectDispatchOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).RejectDispatchOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_RejectDispatchOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).RejectDispatchOffer(ctx, req.(*RejectDispatchOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_StartTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).StartTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_StartTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).StartTrip(ctx, req.(*StartTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_FinishTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).FinishTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_FinishTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).FinishTrip(ctx, req.(*FinishTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetBookingDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetBookingDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_GetBookingDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetBookingDetails(ctx, req.(*GetBookingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingService_ServiceDesc is the grpc.ServiceDesc for BookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking.v1.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookRide",
			Handler:    _BookingService_BookRide_Handler,
		},
		{
			MethodName: "AcceptDispatchOffer",
			Handler:    _BookingService_AcceptDispatchOffer_Handler,
		},
		{
			MethodName: "RejectDispatchOffer",
			Handler:    _BookingService_RejectDispatchOffer_Handler,
		},
		{
			MethodName: "StartTrip",
			Handler:    _BookingService_StartTrip_Handler,
		},
		{
			MethodName: "FinishTrip",
			Handler:    _BookingService_FinishTrip_Handler,
		},
		{
			MethodName: "GetBookingDetails",
			Handler:    _BookingService_GetBookingDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking.proto",
}
