// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: review.proto

package reviewpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReviewService_SubmitRating_FullMethodName  = "/review.v1.ReviewService/SubmitRating"
	ReviewService_GetTripRating_FullMethodName = "/review.v1.ReviewService/GetTripRating"
)

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewServiceClient interface {
	// SubmitRating records a post-trip rating. Returns AlreadyExists if a rating
	// for this trip/role combination already exists.
	SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*RatingProto, error)
	// GetTripRating returns the rating for a trip/role combination.
	// Returns NotFound if no rating has been submitted yet.
	GetTripRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingProto, error)
}

type reviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewServiceClient(cc grpc.ClientConnInterface) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*RatingProto, error) {
	out := new(RatingProto)
	err := c.cc.Invoke(ctx, ReviewService_SubmitRating_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) GetTripRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingProto, error) {
	out := new(RatingProto)
	err := c.cc.Invoke(ctx, ReviewService_GetTripRating_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
// All implementations must embed UnimplementedReviewServiceServer
// for forward compatibility
type ReviewServiceServer interface {
	// SubmitRating records a post-trip rating. Returns AlreadyExists if a rating
	// for this trip/role combination already exists.
	SubmitRating(context.Context, *SubmitRatingRequest) (*RatingProto, error)
	// GetTripRating returns the rating for a trip/role combination.
	// Returns NotFound if no rating has been submitted yet.
	GetTripRating(context.Context, *GetRatingRequest) (*RatingProto, error)
	mustEmbedUnimplementedReviewServiceServer()
}

// UnimplementedReviewServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReviewServiceServer struct {
}

func (UnimplementedReviewServiceServer) SubmitRating(context.Context, *SubmitRatingRequest) (*RatingProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRating not implemented")
}
func (UnimplementedReviewServiceServer) GetTripRating(context.Context, *GetRatingRequest) (*RatingProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTripRating not implemented")
}
func (UnimplementedReviewServiceServer) mustEmbedUnimplementedReviewServiceServer() {}

// UnsafeReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServiceServer will
// result in compilation errors.
type UnsafeReviewServiceServer interface {
	mustEmbedUnimplementedReviewServiceServer()
}

func RegisterReviewServiceServer(s grpc.ServiceRegistrar, srv ReviewServiceServer) {
	s.RegisterService(&ReviewService_ServiceDesc, srv)
}

func _ReviewService_SubmitRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).SubmitRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_SubmitRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).SubmitRating(ctx, req.(*SubmitRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_GetTripRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetTripRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_GetTripRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetTripRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewService_ServiceDesc is the grpc.ServiceDesc for ReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review.v1.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRating",
			Handler:    _ReviewService_SubmitRating_Handler,
		},
		{
			MethodName: "GetTripRating",
			Handler:    _ReviewService_GetTripRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
