// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: availability.proto

package driverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DriverAvailabilityService_GoOnline_FullMethodName        = "/driver.v1.DriverAvailabilityService/GoOnline"
	DriverAvailabilityService_GoOffline_FullMethodName       = "/driver.v1.DriverAvailabilityService/GoOffline"
	DriverAvailabilityService_Heartbeat_FullMethodName       = "/driver.v1.DriverAvailabilityService/Heartbeat"
	DriverAvailabilityService_GetAvailability_FullMethodName = "/driver.v1.DriverAvailabilityService/GetAvailability"
)

// DriverAvailabilityServiceClient is the client API for DriverAvailabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverAvailabilityServiceClient interface {
	// GoOnline marks a driver as online and starts the heartbeat clock.
	GoOnline(ctx context.Context, in *GoOnlineRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// GoOffline explicitly marks a driver as offline.
	GoOffline(ctx context.Context, in *GoOfflineRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// Heartbeat refreshes the online TTL.
	// Returns FailedPrecondition if the driver is not currently online.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// GetAvailability returns the current online status and last-seen timestamp.
	// Returns a zero last_seen timestamp if the driver has never been seen.
	GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
}

type driverAvailabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverAvailabilityServiceClient(cc grpc.ClientConnInterface) DriverAvailabilityServiceClient {
	return &driverAvailabilityServiceClient{cc}
}

func (c *driverAvailabilityServiceClient) GoOnline(ctx context.Context, in *GoOnlineRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, DriverAvailabilityService_GoOnline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAvailabilityServiceClient) GoOffline(ctx context.Context, in *GoOfflineRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, DriverAvailabilityService_GoOffline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAvailabilityServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, DriverAvailabilityService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAvailabilityServiceClient) GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, DriverAvailabilityService_GetAvailability_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverAvailabilityServiceServer is the server API for DriverAvailabilityService service.
// All implementations must embed UnimplementedDriverAvailabilityServiceServer
// for forward compatibility
type DriverAvailabilityServiceServer interface {
	// GoOnline marks a driver as online and starts the heartbeat clock.
	GoOnline(context.Context, *GoOnlineRequest) (*AvailabilityResponse, error)
	// GoOffline explicitly marks a driver as offline.
	GoOffline(context.Context, *GoOfflineRequest) (*AvailabilityResponse, error)
	// Heartbeat refreshes the online TTL.
	// Returns FailedPrecondition if the driver is not currently online.
	Heartbeat(context.Context, *HeartbeatRequest) (*AvailabilityResponse, error)
	// GetAvailability returns the current online status and last-seen timestamp.
	// Returns a zero last_seen timestamp if the driver has never been seen.
	GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error)
	mustEmbedUnimplementedDriverAvailabilityServiceServer()
}

// UnimplementedDriverAvailabilityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDriverAvailabilityServiceServer struct {
}

func (UnimplementedDriverAvailabilityServiceServer) GoOnline(context.Context, *GoOnlineRequest) (*AvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoOnline not implemented")
}
func (UnimplementedDriverAvailabilityServiceServer) GoOffline(context.Context, *GoOfflineRequest) (*AvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoOffline not implemented")
}
func (UnimplementedDriverAvailabilityServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*AvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDriverAvailabilityServiceServer) GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailability not implemented")
}
func (UnimplementedDriverAvailabilityServiceServer) mustEmbedUnimplementedDriverAvailabilityServiceServer() {
}

// UnsafeDriverAvailabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverAvailabilityServiceServer will
// result in compilation errors.
type UnsafeDriverAvailabilityServiceServer interface {
	mustEmbedUnimplementedDriverAvailabilityServiceServer()
}

func RegisterDriverAvailabilityServiceServer(s grpc.ServiceRegistrar, srv DriverAvailabilityServiceServer) {
	s.RegisterService(&DriverAvailabilityService_ServiceDesc, srv)
}

func _DriverAvailabilityService_GoOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAvailabilityServiceServer).GoOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAvailabilityService_GoOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAvailabilityServiceServer).GoOnline(ctx, req.(*GoOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAvailabilityService_GoOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoOfflineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAvailabilityServiceServer).GoOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAvailabilityService_GoOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAvailabilityServiceServer).GoOffline(ctx, req.(*GoOfflineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAvailabilityService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAvailabilityServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAvailabilityService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAvailabilityServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAvailabilityService_GetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAvailabilityServiceServer).GetAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAvailabilityService_GetAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAvailabilityServiceServer).GetAvailability(ctx, req.(*GetAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverAvailabilityService_ServiceDesc is the grpc.ServiceDesc for DriverAvailabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverAvailabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.v1.DriverAvailabilityService",
	HandlerType: (*DriverAvailabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoOnline",
			Handler:    _DriverAvailabilityService_GoOnline_Handler,
		},
		{
			MethodName: "GoOffline",
			Handler:    _DriverAvailabilityService_GoOffline_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DriverAvailabilityService_Heartbeat_Handler,
		},
		{
			MethodName: "GetAvailability",
			Handler:    _DriverAvailabilityService_GetAvailability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "availability.proto",
}
