// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: driver_profile.proto

package driverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DriverProfileService_GetDriverProfile_FullMethodName         = "/driver.v1.DriverProfileService/GetDriverProfile"
	DriverProfileService_GetDriverProfileByUserID_FullMethodName = "/driver.v1.DriverProfileService/GetDriverProfileByUserID"
	DriverProfileService_UpdateDriverProfile_FullMethodName      = "/driver.v1.DriverProfileService/UpdateDriverProfile"
	DriverProfileService_UpdateOnlineStatus_FullMethodName       = "/driver.v1.DriverProfileService/UpdateOnlineStatus"
	DriverProfileService_UpdateVerificationStatus_FullMethodName = "/driver.v1.DriverProfileService/UpdateVerificationStatus"
)

// DriverProfileServiceClient is the client API for DriverProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverProfileServiceClient interface {
	// GetDriverProfile returns a driver profile by its driver_id.
	GetDriverProfile(ctx context.Context, in *GetDriverProfileRequest, opts ...grpc.CallOption) (*GetDriverProfileResponse, error)
	// GetDriverProfileByUserID returns a driver profile by the associated user_id.
	GetDriverProfileByUserID(ctx context.Context, in *GetDriverProfileByUserIDRequest, opts ...grpc.CallOption) (*GetDriverProfileResponse, error)
	// UpdateDriverProfile replaces vehicle info and license number.
	UpdateDriverProfile(ctx context.Context, in *UpdateDriverProfileRequest, opts ...grpc.CallOption) (*UpdateDriverProfileResponse, error)
	// UpdateOnlineStatus sets the driver online or offline.
	// A driver must be verified before they can go online.
	UpdateOnlineStatus(ctx context.Context, in *UpdateOnlineStatusRequest, opts ...grpc.CallOption) (*UpdateOnlineStatusResponse, error)
	// UpdateVerificationStatus transitions the driver verification state.
	// This is an admin-only operation.
	UpdateVerificationStatus(ctx context.Context, in *UpdateVerificationStatusRequest, opts ...grpc.CallOption) (*UpdateVerificationStatusResponse, error)
}

type driverProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverProfileServiceClient(cc grpc.ClientConnInterface) DriverProfileServiceClient {
	return &driverProfileServiceClient{cc}
}

func (c *driverProfileServiceClient) GetDriverProfile(ctx context.Context, in *GetDriverProfileRequest, opts ...grpc.CallOption) (*GetDriverProfileResponse, error) {
	out := new(GetDriverProfileResponse)
	err := c.cc.Invoke(ctx, DriverProfileService_GetDriverProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverProfileServiceClient) GetDriverProfileByUserID(ctx context.Context, in *GetDriverProfileByUserIDRequest, opts ...grpc.CallOption) (*GetDriverProfileResponse, error) {
	out := new(GetDriverProfileResponse)
	err := c.cc.Invoke(ctx, DriverProfileService_GetDriverProfileByUserID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverProfileServiceClient) UpdateDriverProfile(ctx context.Context, in *UpdateDriverProfileRequest, opts ...grpc.CallOption) (*UpdateDriverProfileResponse, error) {
	out := new(UpdateDriverProfileResponse)
	err := c.cc.Invoke(ctx, DriverProfileService_UpdateDriverProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverProfileServiceClient) UpdateOnlineStatus(ctx context.Context, in *UpdateOnlineStatusRequest, opts ...grpc.CallOption) (*UpdateOnlineStatusResponse, error) {
	out := new(UpdateOnlineStatusResponse)
	err := c.cc.Invoke(ctx, DriverProfileService_UpdateOnlineStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverProfileServiceClient) UpdateVerificationStatus(ctx context.Context, in *UpdateVerificationStatusRequest, opts ...grpc.CallOption) (*UpdateVerificationStatusResponse, error) {
	out := new(UpdateVerificationStatusResponse)
	err := c.cc.Invoke(ctx, DriverProfileService_UpdateVerificationStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverProfileServiceServer is the server API for DriverProfileService service.
// All implementations must embed UnimplementedDriverProfileServiceServer
// for forward compatibility
type DriverProfileServiceServer interface {
	// GetDriverProfile returns a driver profile by its driver_id.
	GetDriverProfile(context.Context, *GetDriverProfileRequest) (*GetDriverProfileResponse, error)
	// GetDriverProfileByUserID returns a driver profile by the associated user_id.
	GetDriverProfileByUserID(context.Context, *GetDriverProfileByUserIDRequest) (*GetDriverProfileResponse, error)
	// UpdateDriverProfile replaces vehicle info and license number.
	UpdateDriverProfile(context.Context, *UpdateDriverProfileRequest) (*UpdateDriverProfileResponse, error)
	// UpdateOnlineStatus sets the driver online or offline.
	// A driver must be verified before they can go online.
	UpdateOnlineStatus(context.Context, *UpdateOnlineStatusRequest) (*UpdateOnlineStatusResponse, error)
	// UpdateVerificationStatus transitions the driver verification state.
	// This is an admin-only operation.
	UpdateVerificationStatus(context.Context, *UpdateVerificationStatusRequest) (*UpdateVerificationStatusResponse, error)
	mustEmbedUnimplementedDriverProfileServiceServer()
}

// UnimplementedDriverProfileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDriverProfileServiceServer struct {
}

func (UnimplementedDriverProfileServiceServer) GetDriverProfile(context.Context, *GetDriverProfileRequest) (*GetDriverProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriverProfile not implemented")
}
func (UnimplementedDriverProfileServiceServer) GetDriverProfileByUserID(context.Context, *GetDriverProfileByUserIDRequest) (*GetDriverProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDriverProfileByUserID not implemented")
}
func (UnimplementedDriverProfileServiceServer) UpdateDriverProfile(context.Context, *UpdateDriverProfileRequest) (*UpdateDriverProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDriverProfile not implemented")
}
func (UnimplementedDriverProfileServiceServer) UpdateOnlineStatus(context.Context, *UpdateOnlineStatusRequest) (*UpdateOnlineStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOnlineStatus not implemented")
}
func (UnimplementedDriverProfileServiceServer) UpdateVerificationStatus(context.Context, *UpdateVerificationStatusRequest) (*UpdateVerificationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVerificationStatus not implemented")
}
func (UnimplementedDriverProfileServiceServer) mustEmbedUnimplementedDriverProfileServiceServer() {}

// UnsafeDriverProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverProfileServiceServer will
// result in compilation errors.
type UnsafeDriverProfileServiceServer interface {
	mustEmbedUnimplementedDriverProfileServiceServer()
}

func RegisterDriverProfileServiceServer(s grpc.ServiceRegistrar, srv DriverProfileServiceServer) {
	s.RegisterService(&DriverProfileService_ServiceDesc, srv)
}

func _DriverProfileService_GetDriverProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverProfileServiceServer).GetDriverProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverProfileService_GetDriverProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverProfileServiceServer).GetDriverProfile(ctx, req.(*GetDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverProfileService_GetDriverProfileByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverProfileByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverProfileServiceServer).GetDriverProfileByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverProfileService_GetDriverProfileByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverProfileServiceServer).GetDriverProfileByUserID(ctx, req.(*GetDriverProfileByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverProfileService_UpdateDriverProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverProfileServiceServer).UpdateDriverProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverProfileService_UpdateDriverProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverProfileServiceServer).UpdateDriverProfile(ctx, req.(*UpdateDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverProfileService_UpdateOnlineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOnlineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverProfileServiceServer).UpdateOnlineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverProfileService_UpdateOnlineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverProfileServiceServer).UpdateOnlineStatus(ctx, req.(*UpdateOnlineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverProfileService_UpdateVerificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVerificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverProfileServiceServer).UpdateVerificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverProfileService_UpdateVerificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverProfileServiceServer).UpdateVerificationStatus(ctx, req.(*UpdateVerificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverProfileService_ServiceDesc is the grpc.ServiceDesc for DriverProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.v1.DriverProfileService",
	HandlerType: (*DriverProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDriverProfile",
			Handler:    _DriverProfileService_GetDriverProfile_Handler,
		},
		{
			MethodName: "GetDriverProfileByUserID",
			Handler:    _DriverProfileService_GetDriverProfileByUserID_Handler,
		},
		{
			MethodName: "UpdateDriverProfile",
			Handler:    _DriverProfileService_UpdateDriverProfile_Handler,
		},
		{
			MethodName: "UpdateOnlineStatus",
			Handler:    _DriverProfileService_UpdateOnlineStatus_Handler,
		},
		{
			MethodName: "UpdateVerificationStatus",
			Handler:    _DriverProfileService_UpdateVerificationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver_profile.proto",
}
